-- Turso schema snapshot — generated by scripts/snapshot-turso-schema.mts
-- Generated at: 2026-05-08T23:37:29.420Z
-- DO NOT edit by hand. Re-run the snapshot script after migrations.

CREATE TABLE "AuditLog" (
        "id" TEXT PRIMARY KEY,
        "actorUserId" TEXT,
        "actorEmail" TEXT,
        "action" TEXT NOT NULL,
        "entityType" TEXT NOT NULL,
        "entityId" TEXT NOT NULL,
        "oldValue" TEXT,
        "newValue" TEXT,
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
CREATE TABLE "Blitz" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "location" TEXT NOT NULL DEFAULT '',
    "housing" TEXT NOT NULL DEFAULT '',
    "startDate" TEXT NOT NULL,
    "endDate" TEXT NOT NULL,
    "notes" TEXT NOT NULL DEFAULT '',
    "status" TEXT NOT NULL DEFAULT 'upcoming',
    "createdById" TEXT NOT NULL,
    "ownerId" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Blitz_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Blitz_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE "BlitzCost" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "blitzId" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "description" TEXT NOT NULL DEFAULT '',
    "date" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL, "amountCents" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "BlitzCost_blitzId_fkey" FOREIGN KEY ("blitzId") REFERENCES "Blitz" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE "BlitzParticipant" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "blitzId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "joinStatus" TEXT NOT NULL DEFAULT 'pending',
    "attendanceStatus" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "BlitzParticipant_blitzId_fkey" FOREIGN KEY ("blitzId") REFERENCES "Blitz" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "BlitzParticipant_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE "BlitzRequest" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "requestedById" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "location" TEXT NOT NULL DEFAULT '',
    "startDate" TEXT NOT NULL,
    "endDate" TEXT NOT NULL,
    "housing" TEXT NOT NULL DEFAULT '',
    "notes" TEXT NOT NULL DEFAULT '',
    "expectedHeadcount" INTEGER NOT NULL DEFAULT 0,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "adminNotes" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL, type TEXT NOT NULL DEFAULT 'create', blitzId TEXT,
    CONSTRAINT "BlitzRequest_requestedById_fkey" FOREIGN KEY ("requestedById") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE "DataAccessLog" (
        "id"              TEXT     PRIMARY KEY,
        "actorUserId"     TEXT     NOT NULL,
        "effectiveUserId" TEXT,
        "route"           TEXT     NOT NULL,
        "modelName"       TEXT     NOT NULL,
        "recordIdsJson"   TEXT     NOT NULL,
        "recordCount"     INTEGER  NOT NULL,
        "createdAt"       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
CREATE TABLE "EmailDelivery" (
        "id"                TEXT PRIMARY KEY NOT NULL,
        "projectId"         TEXT NOT NULL,
        "installerId"       TEXT,
        "providerMessageId" TEXT,
        "toEmails"          TEXT NOT NULL,
        "ccEmails"          TEXT NOT NULL,
        "subject"           TEXT NOT NULL,
        "status"            TEXT NOT NULL,
        "errorReason"       TEXT,
        "sentAt"            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "deliveredAt"       DATETIME,
        "bouncedAt"         DATETIME,
        "isTest"            INTEGER NOT NULL DEFAULT 0,
        "createdById"       TEXT NOT NULL,
        CONSTRAINT "EmailDelivery_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE,
        CONSTRAINT "EmailDelivery_installerId_fkey" FOREIGN KEY ("installerId") REFERENCES "Installer"("id") ON DELETE SET NULL ON UPDATE CASCADE,
        CONSTRAINT "EmailDelivery_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE CASCADE
      );
CREATE TABLE "Feedback" (
        "id" TEXT NOT NULL PRIMARY KEY,
        "userId" TEXT NOT NULL,
        "userRoleSnapshot" TEXT NOT NULL,
        "message" TEXT NOT NULL,
        "url" TEXT,
        "userAgent" TEXT,
        "resolved" INTEGER NOT NULL DEFAULT 0,
        "resolvedAt" DATETIME,
        "resolvedBy" TEXT,
        "resolverNote" TEXT,
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "Feedback_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE
      );
CREATE TABLE "Financer" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
CREATE TABLE "Incentive" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL DEFAULT '',
    "type" TEXT NOT NULL,
    "metric" TEXT NOT NULL,
    "period" TEXT NOT NULL,
    "startDate" TEXT NOT NULL,
    "endDate" TEXT,
    "targetRepId" TEXT,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "blitzId" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Incentive_targetRepId_fkey" FOREIGN KEY ("targetRepId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "Incentive_blitzId_fkey" FOREIGN KEY ("blitzId") REFERENCES "Blitz" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE TABLE "IncentiveMilestone" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "incentiveId" TEXT NOT NULL,
    "threshold" REAL NOT NULL,
    "reward" TEXT NOT NULL,
    "achieved" BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT "IncentiveMilestone_incentiveId_fkey" FOREIGN KEY ("incentiveId") REFERENCES "Incentive" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE "Installer" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "installPayPct" INTEGER NOT NULL DEFAULT 80,
    "usesProductCatalog" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
, "primaryEmail" TEXT, "ccEmails" TEXT NOT NULL DEFAULT '[]', "subjectPrefix" TEXT, "handoffEnabled" INTEGER NOT NULL DEFAULT 0, "customNotes" TEXT NOT NULL DEFAULT '');
CREATE TABLE "InstallerPrepaidOption" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "installerId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "InstallerPrepaidOption_installerId_fkey" FOREIGN KEY ("installerId") REFERENCES "Installer" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE "InstallerPricingTier" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "versionId" TEXT NOT NULL,
    "minKW" REAL NOT NULL DEFAULT 0,
    "maxKW" REAL,
    "closerPerW" REAL NOT NULL,
    "setterPerW" REAL,
    "kiloPerW" REAL NOT NULL,
    "subDealerPerW" REAL,
    CONSTRAINT "InstallerPricingTier_versionId_fkey" FOREIGN KEY ("versionId") REFERENCES "InstallerPricingVersion" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE "InstallerPricingVersion" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "installerId" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "effectiveFrom" TEXT NOT NULL,
    "effectiveTo" TEXT,
    "rateType" TEXT NOT NULL DEFAULT 'flat',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "InstallerPricingVersion_installerId_fkey" FOREIGN KEY ("installerId") REFERENCES "Installer" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE "NotificationDelivery" (
        "id"                TEXT PRIMARY KEY NOT NULL,
        "userId"            TEXT,
        "eventType"         TEXT NOT NULL,
        "channel"           TEXT NOT NULL,
        "toAddress"         TEXT NOT NULL,
        "providerMessageId" TEXT,
        "status"            TEXT NOT NULL,
        "errorReason"       TEXT,
        "payloadJson"       TEXT,
        "projectId"         TEXT,
        "sentAt"            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "deliveredAt"       DATETIME,
        "bouncedAt"         DATETIME,
        CONSTRAINT "NotificationDelivery_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE,
        CONSTRAINT "NotificationDelivery_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE SET NULL ON UPDATE CASCADE
      );
CREATE TABLE "NotificationPreference" (
        "id"           TEXT PRIMARY KEY NOT NULL,
        "userId"       TEXT NOT NULL,
        "eventType"    TEXT NOT NULL,
        "emailEnabled" INTEGER NOT NULL DEFAULT 1,
        "smsEnabled"   INTEGER NOT NULL DEFAULT 0,
        "pushEnabled"  INTEGER NOT NULL DEFAULT 0,
        "digestMode"   TEXT NOT NULL DEFAULT 'instant',
        "updatedAt"    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "NotificationPreference_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
      );
CREATE TABLE "PayrollEntry" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "repId" TEXT NOT NULL,
    "projectId" TEXT,
    "type" TEXT NOT NULL,
    "paymentStage" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'Draft',
    "date" TEXT NOT NULL,
    "notes" TEXT NOT NULL DEFAULT '',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL, "idempotencyKey" TEXT, "amountCents" INTEGER NOT NULL DEFAULT 0, "paidAt" DATETIME, "isChargeback" BOOLEAN NOT NULL DEFAULT 0, "chargebackOfId" TEXT, "originalAmountCents" INTEGER, "editedAfterPaidAt" DATETIME, "editedBy" TEXT, "editReason" TEXT,
    CONSTRAINT "PayrollEntry_repId_fkey" FOREIGN KEY ("repId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "PayrollEntry_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE TABLE "Product" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "installerId" TEXT NOT NULL,
    "family" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Product_installerId_fkey" FOREIGN KEY ("installerId") REFERENCES "Installer" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE "ProductCatalogConfig" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "installerId" TEXT NOT NULL,
    "families" TEXT NOT NULL DEFAULT '',
    "familyFinancerMap" TEXT NOT NULL DEFAULT '{}',
    "prepaidFamily" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "ProductCatalogConfig_installerId_fkey" FOREIGN KEY ("installerId") REFERENCES "Installer" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE "ProductPricingTier" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "versionId" TEXT NOT NULL,
    "minKW" REAL NOT NULL,
    "maxKW" REAL,
    "closerPerW" REAL NOT NULL,
    "setterPerW" REAL NOT NULL,
    "kiloPerW" REAL NOT NULL,
    "subDealerPerW" REAL,
    CONSTRAINT "ProductPricingTier_versionId_fkey" FOREIGN KEY ("versionId") REFERENCES "ProductPricingVersion" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE "ProductPricingVersion" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "productId" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "effectiveFrom" TEXT NOT NULL,
    "effectiveTo" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "ProductPricingVersion_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE "Project" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "customerName" TEXT NOT NULL,
    "closerId" TEXT NOT NULL,
    "setterId" TEXT,
    "subDealerId" TEXT,
    "soldDate" TEXT NOT NULL,
    "installerId" TEXT NOT NULL,
    "financerId" TEXT NOT NULL,
    "productType" TEXT NOT NULL,
    "kWSize" REAL NOT NULL,
    "netPPW" REAL NOT NULL,
    "phase" TEXT NOT NULL DEFAULT 'New',
    "m1Paid" BOOLEAN NOT NULL DEFAULT false,
    "m2Paid" BOOLEAN NOT NULL DEFAULT false,
    "notes" TEXT NOT NULL DEFAULT '',
    "flagged" BOOLEAN NOT NULL DEFAULT false,
    "installerPricingVersionId" TEXT,
    "productId" TEXT,
    "productPricingVersionId" TEXT,
    "baselineOverrideJson" TEXT,
    "prepaidSubType" TEXT,
    "leadSource" TEXT,
    "blitzId" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL, "m3Paid" BOOLEAN NOT NULL DEFAULT false, "cancellationReason" TEXT, "cancellationNotes" TEXT, "m1AmountCents" INTEGER NOT NULL DEFAULT 0, "m2AmountCents" INTEGER NOT NULL DEFAULT 0, "m3AmountCents" INTEGER, "setterM1AmountCents" INTEGER NOT NULL DEFAULT 0, "setterM2AmountCents" INTEGER NOT NULL DEFAULT 0, "setterM3AmountCents" INTEGER, "trainerId" TEXT REFERENCES "User"("id"), "trainerRate" REAL, "phaseChangedAt" DATETIME, "importedFromGlide" BOOLEAN NOT NULL DEFAULT 0, "adminNotes" TEXT NOT NULL DEFAULT '', "installerIntakeJson" TEXT, "handoffSentAt" DATETIME, "handoffLastResendAt" DATETIME, "utilityBillFileId" TEXT, "noChainTrainer" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "Project_closerId_fkey" FOREIGN KEY ("closerId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Project_setterId_fkey" FOREIGN KEY ("setterId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "Project_subDealerId_fkey" FOREIGN KEY ("subDealerId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "Project_installerId_fkey" FOREIGN KEY ("installerId") REFERENCES "Installer" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Project_financerId_fkey" FOREIGN KEY ("financerId") REFERENCES "Financer" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Project_installerPricingVersionId_fkey" FOREIGN KEY ("installerPricingVersionId") REFERENCES "InstallerPricingVersion" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "Project_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "Project_productPricingVersionId_fkey" FOREIGN KEY ("productPricingVersionId") REFERENCES "ProductPricingVersion" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "Project_blitzId_fkey" FOREIGN KEY ("blitzId") REFERENCES "Blitz" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE TABLE "ProjectActivity" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "projectId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "detail" TEXT NOT NULL,
    "meta" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ProjectActivity_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE "ProjectAdminNote" (
        "id"         TEXT PRIMARY KEY NOT NULL,
        "projectId"  TEXT NOT NULL,
        "authorId"   TEXT NOT NULL,
        "authorName" TEXT NOT NULL,
        "text"       TEXT NOT NULL,
        "createdAt"  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "ProjectAdminNote_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE
      );
CREATE TABLE "ProjectCheckItem" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "messageId" TEXT NOT NULL,
    "text" TEXT NOT NULL,
    "completed" BOOLEAN NOT NULL DEFAULT false,
    "completedBy" TEXT,
    "completedAt" DATETIME,
    "dueDate" DATETIME,
    CONSTRAINT "ProjectCheckItem_messageId_fkey" FOREIGN KEY ("messageId") REFERENCES "ProjectMessage" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE "ProjectCloser" (
        "id" TEXT NOT NULL PRIMARY KEY,
        "projectId" TEXT NOT NULL,
        "userId" TEXT NOT NULL,
        "m1AmountCents" INTEGER NOT NULL DEFAULT 0,
        "m2AmountCents" INTEGER NOT NULL DEFAULT 0,
        "m3AmountCents" INTEGER,
        "position" INTEGER NOT NULL DEFAULT 1,
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" DATETIME NOT NULL,
        CONSTRAINT "ProjectCloser_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE,
        CONSTRAINT "ProjectCloser_userId_fkey"    FOREIGN KEY ("userId")    REFERENCES "User"("id")    ON DELETE RESTRICT ON UPDATE CASCADE
      );
CREATE TABLE "ProjectFile" (
        "id"           TEXT PRIMARY KEY NOT NULL,
        "projectId"    TEXT NOT NULL,
        "kind"         TEXT NOT NULL,
        "label"        TEXT NOT NULL,
        "originalName" TEXT NOT NULL,
        "blobUrl"      TEXT NOT NULL,
        "blobPath"     TEXT NOT NULL,
        "mimeType"     TEXT NOT NULL,
        "sizeBytes"    INTEGER NOT NULL,
        "uploadedById" TEXT NOT NULL,
        "createdAt"    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "ProjectFile_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE,
        CONSTRAINT "ProjectFile_uploadedById_fkey" FOREIGN KEY ("uploadedById") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE CASCADE
      );
CREATE TABLE "ProjectInstallerNote" (
        "id"        TEXT PRIMARY KEY NOT NULL,
        "projectId" TEXT NOT NULL,
        "body"      TEXT NOT NULL,
        "authorId"  TEXT NOT NULL,
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "ProjectInstallerNote_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE,
        CONSTRAINT "ProjectInstallerNote_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE CASCADE
      );
CREATE TABLE "ProjectMention" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "messageId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "readAt" DATETIME,
    CONSTRAINT "ProjectMention_messageId_fkey" FOREIGN KEY ("messageId") REFERENCES "ProjectMessage" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE "ProjectMessage" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "projectId" TEXT NOT NULL,
    "authorId" TEXT NOT NULL,
    "authorName" TEXT NOT NULL,
    "authorRole" TEXT NOT NULL,
    "text" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ProjectMessage_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE "ProjectNote" (
        "id"         TEXT PRIMARY KEY NOT NULL,
        "projectId"  TEXT NOT NULL,
        "authorId"   TEXT NOT NULL,
        "authorName" TEXT NOT NULL,
        "text"       TEXT NOT NULL,
        "createdAt"  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "ProjectNote_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE
      );
CREATE TABLE "ProjectSetter" (
        "id" TEXT NOT NULL PRIMARY KEY,
        "projectId" TEXT NOT NULL,
        "userId" TEXT NOT NULL,
        "m1AmountCents" INTEGER NOT NULL DEFAULT 0,
        "m2AmountCents" INTEGER NOT NULL DEFAULT 0,
        "m3AmountCents" INTEGER,
        "position" INTEGER NOT NULL DEFAULT 1,
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" DATETIME NOT NULL,
        CONSTRAINT "ProjectSetter_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE,
        CONSTRAINT "ProjectSetter_userId_fkey"    FOREIGN KEY ("userId")    REFERENCES "User"("id")    ON DELETE RESTRICT ON UPDATE CASCADE
      );
CREATE TABLE "ProjectSurveyLink" (
        "id"        TEXT PRIMARY KEY NOT NULL,
        "projectId" TEXT NOT NULL,
        "url"       TEXT NOT NULL,
        "label"     TEXT NOT NULL,
        "addedById" TEXT NOT NULL,
        "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "ProjectSurveyLink_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE,
        CONSTRAINT "ProjectSurveyLink_addedById_fkey" FOREIGN KEY ("addedById") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE CASCADE
      );
CREATE TABLE "PushSubscription" (
        "id"          TEXT PRIMARY KEY NOT NULL,
        "userId"      TEXT NOT NULL,
        "provider"    TEXT NOT NULL DEFAULT 'web_push',
        "endpoint"    TEXT NOT NULL,
        "p256dh"      TEXT,
        "auth"        TEXT,
        "nativeToken" TEXT,
        "userAgent"   TEXT,
        "createdAt"   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "lastSeenAt"  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "PushSubscription_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
      );
CREATE TABLE "Reimbursement" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "repId" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "date" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'Pending',
    "receiptName" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL, "amountCents" INTEGER NOT NULL DEFAULT 0, "receiptUrl" TEXT, "archivedAt" DATETIME,
    CONSTRAINT "Reimbursement_repId_fkey" FOREIGN KEY ("repId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE "StalledAlertConfig" (
        "id"                 TEXT PRIMARY KEY NOT NULL DEFAULT 'singleton',
        "enabled"            INTEGER NOT NULL DEFAULT 1,
        "soldDateCutoffDays" INTEGER NOT NULL DEFAULT 180,
        "digestRecipients"   TEXT NOT NULL DEFAULT '[]',
        "phaseThresholds"    TEXT NOT NULL DEFAULT '{}',
        "digestSendHourUtc"  INTEGER NOT NULL DEFAULT 15,
        "updatedAt"          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedById"        TEXT
      );
CREATE TABLE "TrainerAssignment" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "trainerId" TEXT NOT NULL,
    "traineeId" TEXT NOT NULL,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL, "isActiveTraining" BOOLEAN NOT NULL DEFAULT true,
    CONSTRAINT "TrainerAssignment_trainerId_fkey" FOREIGN KEY ("trainerId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "TrainerAssignment_traineeId_fkey" FOREIGN KEY ("traineeId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE "TrainerOverrideTier" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "assignmentId" TEXT NOT NULL,
    "upToDeal" INTEGER,
    "ratePerW" REAL NOT NULL,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "TrainerOverrideTier_assignmentId_fkey" FOREIGN KEY ("assignmentId") REFERENCES "TrainerAssignment" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE "User" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "firstName" TEXT NOT NULL,
    "lastName" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "phone" TEXT NOT NULL DEFAULT '',
    "role" TEXT NOT NULL DEFAULT 'rep',
    "repType" TEXT NOT NULL DEFAULT 'both',
    "active" BOOLEAN NOT NULL DEFAULT true,
    "canRequestBlitz" BOOLEAN NOT NULL DEFAULT false,
    "canCreateBlitz" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
, canExport BOOLEAN NOT NULL DEFAULT false, canCreateDeals BOOLEAN NOT NULL DEFAULT false, canAccessBlitz BOOLEAN NOT NULL DEFAULT false, "clerkUserId" TEXT, "scopedInstallerId" TEXT, "notificationPhone" TEXT, "notificationPhoneVerifiedAt" DATETIME, "quietHoursStartUtc" INTEGER, "quietHoursEndUtc" INTEGER);

CREATE INDEX "AuditLog_actorUserId_idx" ON "AuditLog"("actorUserId");
CREATE INDEX "AuditLog_createdAt_idx" ON "AuditLog"("createdAt");
CREATE INDEX "AuditLog_entityType_entityId_idx" ON "AuditLog"("entityType", "entityId");
CREATE INDEX "BlitzCost_blitzId_idx" ON "BlitzCost"("blitzId");
CREATE INDEX "BlitzParticipant_blitzId_idx" ON "BlitzParticipant"("blitzId");
CREATE UNIQUE INDEX "BlitzParticipant_blitzId_userId_key" ON "BlitzParticipant"("blitzId", "userId");
CREATE INDEX "BlitzParticipant_userId_idx" ON "BlitzParticipant"("userId");
CREATE INDEX "BlitzRequest_requestedById_idx" ON "BlitzRequest"("requestedById");
CREATE INDEX "BlitzRequest_status_idx" ON "BlitzRequest"("status");
CREATE INDEX "Blitz_ownerId_idx" ON "Blitz"("ownerId");
CREATE INDEX "Blitz_startDate_idx" ON "Blitz"("startDate");
CREATE INDEX "Blitz_status_idx" ON "Blitz"("status");
CREATE INDEX "DataAccessLog_actorUserId_createdAt_idx" ON "DataAccessLog"("actorUserId", "createdAt");
CREATE INDEX "DataAccessLog_createdAt_idx" ON "DataAccessLog"("createdAt");
CREATE INDEX "DataAccessLog_modelName_createdAt_idx" ON "DataAccessLog"("modelName", "createdAt");
CREATE INDEX "EmailDelivery_createdById_idx" ON "EmailDelivery"("createdById");
CREATE INDEX "EmailDelivery_installerId_idx" ON "EmailDelivery"("installerId");
CREATE INDEX "EmailDelivery_projectId_idx" ON "EmailDelivery"("projectId");
CREATE UNIQUE INDEX "EmailDelivery_providerMessageId_key" ON "EmailDelivery"("providerMessageId");
CREATE INDEX "Feedback_createdAt_idx" ON "Feedback"("createdAt");
CREATE INDEX "Feedback_resolved_createdAt_idx" ON "Feedback"("resolved", "createdAt");
CREATE INDEX "Feedback_userId_idx" ON "Feedback"("userId");
CREATE UNIQUE INDEX "Financer_name_key" ON "Financer"("name");
CREATE INDEX "IncentiveMilestone_incentiveId_idx" ON "IncentiveMilestone"("incentiveId");
CREATE INDEX "Incentive_active_idx" ON "Incentive"("active");
CREATE INDEX "Incentive_blitzId_idx" ON "Incentive"("blitzId");
CREATE INDEX "Incentive_targetRepId_idx" ON "Incentive"("targetRepId");
CREATE UNIQUE INDEX "InstallerPrepaidOption_installerId_name_key" ON "InstallerPrepaidOption"("installerId", "name");
CREATE INDEX "InstallerPricingTier_versionId_idx" ON "InstallerPricingTier"("versionId");
CREATE INDEX "InstallerPricingVersion_installerId_effectiveFrom_idx" ON "InstallerPricingVersion"("installerId", "effectiveFrom");
CREATE INDEX "Installer_active_idx" ON "Installer"("active");
CREATE UNIQUE INDEX "Installer_name_key" ON "Installer"("name");
CREATE INDEX "NotificationDelivery_eventType_sentAt_idx" ON "NotificationDelivery"("eventType", "sentAt");
CREATE INDEX "NotificationDelivery_projectId_idx" ON "NotificationDelivery"("projectId");
CREATE UNIQUE INDEX "NotificationDelivery_providerMessageId_key" ON "NotificationDelivery"("providerMessageId");
CREATE INDEX "NotificationDelivery_userId_idx" ON "NotificationDelivery"("userId");
CREATE UNIQUE INDEX "NotificationPreference_userId_eventType_key" ON "NotificationPreference"("userId", "eventType");
CREATE INDEX "NotificationPreference_userId_idx" ON "NotificationPreference"("userId");
CREATE INDEX "PayrollEntry_chargebackOfId_idx" ON "PayrollEntry"("chargebackOfId");
CREATE INDEX "PayrollEntry_date_idx" ON "PayrollEntry"("date");
CREATE UNIQUE INDEX "PayrollEntry_idempotencyKey_key" ON "PayrollEntry"("idempotencyKey");
CREATE INDEX "PayrollEntry_isChargeback_idx" ON "PayrollEntry"("isChargeback");
CREATE INDEX "PayrollEntry_projectId_idx" ON "PayrollEntry"("projectId");
CREATE INDEX "PayrollEntry_repId_idx" ON "PayrollEntry"("repId");
CREATE INDEX "PayrollEntry_status_idx" ON "PayrollEntry"("status");
CREATE UNIQUE INDEX "ProductCatalogConfig_installerId_key" ON "ProductCatalogConfig"("installerId");
CREATE INDEX "ProductPricingTier_versionId_idx" ON "ProductPricingTier"("versionId");
CREATE INDEX "ProductPricingVersion_productId_effectiveFrom_idx" ON "ProductPricingVersion"("productId", "effectiveFrom");
CREATE INDEX "Product_installerId_active_idx" ON "Product"("installerId", "active");
CREATE INDEX "Product_installerId_family_idx" ON "Product"("installerId", "family");
CREATE INDEX "ProjectActivity_projectId_idx" ON "ProjectActivity"("projectId");
CREATE INDEX "ProjectAdminNote_authorId_idx" ON "ProjectAdminNote"("authorId");
CREATE INDEX "ProjectAdminNote_projectId_idx" ON "ProjectAdminNote"("projectId");
CREATE INDEX "ProjectCheckItem_messageId_idx" ON "ProjectCheckItem"("messageId");
CREATE INDEX "ProjectCloser_projectId_idx" ON "ProjectCloser"("projectId");
CREATE UNIQUE INDEX "ProjectCloser_projectId_userId_key" ON "ProjectCloser"("projectId", "userId");
CREATE INDEX "ProjectCloser_userId_idx" ON "ProjectCloser"("userId");
CREATE INDEX "ProjectFile_kind_idx" ON "ProjectFile"("kind");
CREATE INDEX "ProjectFile_projectId_idx" ON "ProjectFile"("projectId");
CREATE INDEX "ProjectFile_uploadedById_idx" ON "ProjectFile"("uploadedById");
CREATE INDEX "ProjectInstallerNote_authorId_idx" ON "ProjectInstallerNote"("authorId");
CREATE INDEX "ProjectInstallerNote_projectId_idx" ON "ProjectInstallerNote"("projectId");
CREATE INDEX "ProjectMention_messageId_idx" ON "ProjectMention"("messageId");
CREATE INDEX "ProjectMention_userId_idx" ON "ProjectMention"("userId");
CREATE INDEX "ProjectMessage_projectId_idx" ON "ProjectMessage"("projectId");
CREATE INDEX "ProjectNote_authorId_idx" ON "ProjectNote"("authorId");
CREATE INDEX "ProjectNote_projectId_idx" ON "ProjectNote"("projectId");
CREATE INDEX "ProjectSetter_projectId_idx" ON "ProjectSetter"("projectId");
CREATE UNIQUE INDEX "ProjectSetter_projectId_userId_key" ON "ProjectSetter"("projectId", "userId");
CREATE INDEX "ProjectSetter_userId_idx" ON "ProjectSetter"("userId");
CREATE INDEX "ProjectSurveyLink_addedById_idx" ON "ProjectSurveyLink"("addedById");
CREATE INDEX "ProjectSurveyLink_projectId_idx" ON "ProjectSurveyLink"("projectId");
CREATE INDEX "Project_blitzId_idx" ON "Project"("blitzId");
CREATE INDEX "Project_closerId_idx" ON "Project"("closerId");
CREATE INDEX "Project_installerId_idx" ON "Project"("installerId");
CREATE INDEX "Project_phase_idx" ON "Project"("phase");
CREATE INDEX "Project_setterId_idx" ON "Project"("setterId");
CREATE INDEX "Project_soldDate_idx" ON "Project"("soldDate");
CREATE INDEX "Project_subDealerId_idx" ON "Project"("subDealerId");
CREATE INDEX "Project_trainerId_idx" ON "Project"("trainerId");
CREATE UNIQUE INDEX "PushSubscription_endpoint_key" ON "PushSubscription"("endpoint");
CREATE INDEX "PushSubscription_userId_idx" ON "PushSubscription"("userId");
CREATE INDEX "Reimbursement_archivedAt_idx" ON "Reimbursement"("archivedAt");
CREATE INDEX "Reimbursement_repId_idx" ON "Reimbursement"("repId");
CREATE INDEX "Reimbursement_status_idx" ON "Reimbursement"("status");
CREATE INDEX "TrainerAssignment_traineeId_idx" ON "TrainerAssignment"("traineeId");
CREATE INDEX "TrainerAssignment_trainerId_idx" ON "TrainerAssignment"("trainerId");
CREATE UNIQUE INDEX "TrainerAssignment_trainerId_traineeId_key" ON "TrainerAssignment"("trainerId", "traineeId");
CREATE INDEX "TrainerOverrideTier_assignmentId_idx" ON "TrainerOverrideTier"("assignmentId");
CREATE INDEX "User_active_idx" ON "User"("active");
CREATE INDEX "User_clerkUserId_idx" ON "User"("clerkUserId");
CREATE UNIQUE INDEX "User_clerkUserId_key" ON "User"("clerkUserId");
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE INDEX "User_role_idx" ON "User"("role");
