/**
 * Pulls the live Turso schema (CREATE TABLE + CREATE INDEX statements) and
 * writes them to turso-schema.sql. Run this whenever Prisma schema changes
 * land OR a migration is applied directly to Turso, so the checked-in
 * snapshot stays in sync with reality.
 *
 * The snapshot is the input to scripts/check-schema-drift.mjs (the CI gate).
 * If this snapshot is stale, the gate is lying. Refresh first, gate second.
 *
 * Usage:
 *   set -a && . ./.env && set +a    # load TURSO_* env vars
 *   tsx scripts/snapshot-turso-schema.mts
 *   git diff turso-schema.sql       # see what drifted
 */

import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createClient } from '@libsql/client';

const url = process.env.TURSO_DATABASE_URL;
const authToken = process.env.TURSO_AUTH_TOKEN;
if (!url || !authToken) {
  console.error('TURSO_DATABASE_URL and TURSO_AUTH_TOKEN must be set.');
  process.exit(1);
}

const client = createClient({ url, authToken });

async function main(): Promise<void> {
  const result = await client.execute({
    sql: `
      SELECT type, name, sql
      FROM sqlite_master
      WHERE sql IS NOT NULL
        AND name NOT LIKE 'sqlite_%'
        AND name NOT LIKE '_litestream_%'
      ORDER BY type DESC, name ASC
    `,
    args: [],
  });

  const tables: string[] = [];
  const indexes: string[] = [];
  for (const row of result.rows) {
    const type = String(row.type);
    const sql = String(row.sql).trim();
    if (type === 'table') tables.push(sql + ';');
    else if (type === 'index') indexes.push(sql + ';');
  }

  const lines: string[] = [];
  lines.push('-- Turso schema snapshot — generated by scripts/snapshot-turso-schema.mts');
  lines.push(`-- Generated at: ${new Date().toISOString()}`);
  lines.push('-- DO NOT edit by hand. Re-run the snapshot script after migrations.');
  lines.push('');
  lines.push(...tables);
  lines.push('');
  lines.push(...indexes);
  lines.push('');

  const here = dirname(fileURLToPath(import.meta.url));
  const target = join(here, '..', 'turso-schema.sql');
  writeFileSync(target, lines.join('\n'), 'utf-8');

  console.log(`Wrote ${tables.length} tables and ${indexes.length} indexes to turso-schema.sql.`);
}

main().catch((err) => {
  console.error('Snapshot failed:', err);
  process.exit(1);
});
